### ISSUE TITLE
 pyo3 0.22 Support

### ISSUE THREAD

**Issue by Zheaoli** [PyO3/pyo3-async-runtimes#11]
## 🐛 Bug Reports

https://github.com/apache/opendal/issues/5224

In some third party library, we are trying to support Python 3.13. we need update the PyO3 to a version larger than 0.22

For now, https://crates.io/crates/pyo3-async-runtimes/0.21.0/dependencies this lib is lock pyo3 to 0.21

So, Should we consider update the [pyo3-async-runtimes](https://github.com/PyO3/pyo3-async-runtimes) to 0.22.x support?

**Comment by cpu** [comment]
:wave: I was also looking into this recently.

0.22 support was merged to main in https://github.com/PyO3/pyo3-async-runtimes/pull/7, however the documentation still needs updating and the `Cargo.toml` version bumped for a proper release (see https://github.com/PyO3/pyo3-async-runtimes/pull/9).

You could use a Cargo patch in the meantime:

```toml
[patch.crates-io]
# TODO(XXX): remove once pyo3-async-runtimes cuts a 0.22 release.
pyo3-async-runtimes  = { git = 'https://github.com/PyO3/pyo3-async-runtimes.git', rev = '284bd36d0426a988026f878cae22abdb179795e6' }
```
